__all__ = (
    "DreamweaverExtensionType",
    "DREAMWEAVER_EXTENSION_TYPES",
    "is_valid_dreamweaver_extension_type",
)

from typing import Final, Literal, TypeGuard

DreamweaverExtensionType = Literal[
    "behavior",
    "browserprofile",
    "codehint codesnippet",
    "coloringscheme",
    "command",
    "connection",
    "datasource",
    "dictionary",
    "documenttype",
    "encoding",
    "flashbuttonstyle",
    "flashelement",
    "floater",
    "insertbar",
    "jsextension",
    "keyboard shortcut",
    "object",
    "plugin",
    "propertyinspector",
    "report",
    "referencebook",
    "samplecontent",
    "serverbehavior",
    "serverformat",
    "servermodel",
    "site",
    "suite",
    "taglibrary",
    "template",
    "thirdpartytags",
    "toolbar",
    "translator",
    "utility",
    "query",
]

DREAMWEAVER_EXTENSION_TYPES: Final[tuple[DreamweaverExtensionType, ...]] = (
    "behavior",
    "browserprofile",
    "codehint codesnippet",
    "coloringscheme",
    "command",
    "connection",
    "datasource",
    "dictionary",
    "documenttype",
    "encoding",
    "flashbuttonstyle",
    "flashelement",
    "floater",
    "insertbar",
    "jsextension",
    "keyboard shortcut",
    "object",
    "plugin",
    "propertyinspector",
    "report",
    "referencebook",
    "samplecontent",
    "serverbehavior",
    "serverformat",
    "servermodel",
    "site",
    "suite",
    "taglibrary",
    "template",
    "thirdpartytags",
    "toolbar",
    "translator",
    "utility",
    "query",
)


def is_valid_dreamweaver_extension_type(
    extension_type: str,
) -> TypeGuard[DreamweaverExtensionType]:
    return extension_type in DREAMWEAVER_EXTENSION_TYPES
